### ISSUE TITLE
Cover image is duplicated when playback window is at bottom

### ISSUE THREAD

**Issue by diegoulloao** [aome510/spotify-player#498]
**Describe the bug**
A duplicated cover image appears inside the playlist when the playback window position is at bottom.

**To Reproduce**
1. Set playback window at bottom: `playback_window_position = "Bottom"`
2. Play something

**Expected behaviour**
See a single image in the playback window, no duplicated ones.

**Screenshots**
<img width="1440" alt="Screenshot 6" src="https://github.com/aome510/spotify-player/assets/45423661/fd24c50a-aa96-40d9-97bb-f32e82fee105">

**Environment**

- OS: macOs
- Application version: 0.19.1 (up to date version)
- Application features: image, daemon

**Additional context**
```toml
theme = "neofusion"
client_id = "secret"
enable_media_control = true
cover_img_length = 14
page_size_in_rows = 14
playback_window_position = "Bottom"
play_icon = ""
pause_icon = ""

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
```

** Only happening in Kitty terminal (0.35.2).

**Comment by diegoulloao** [comment]
BTW, check this: https://github.com/diegoulloao/neofusion.sp

**Comment by aome510** [comment]
How frequent does this happen and did it ever happen with the previous version `v0.18.2`?

Related: https://github.com/aome510/spotify-player/issues/399. I thought I already fixed it before 🤔

**Comment by diegoulloao** [comment]
I didn’t checked the previous version, I started to change the config after upgrade.

It happen all the time.

**Comment by diegoulloao** [comment]
@aome510 is also happening in the previous version `0.18.2`

**Comment by HiFiveJazz** [comment]
I can also second this bug, I can replicate it on macOS and Linux , given the playback window is at the bottom.

**Comment by diegoulloao** [comment]
<img width="1440" alt="Screenshot" src="https://github.com/user-attachments/assets/4f05323f-687c-43d8-8b5a-b1e8dc6b1640">

Issue persist in latest version `0.19.1` @aome510

**Comment by aome510** [comment]
> <img alt="Screenshot" width="1440" src="https://private-user-images.githubusercontent.com/45423661/361169870-4f05323f-687c-43d8-8b5a-b1e8dc6b1640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MzIxNDksIm5iZiI6MTcyNDUzMTg0OSwicGF0aCI6Ii80NTQyMzY2MS8zNjExNjk4NzAtNGYwNTMyM2YtNjg3Yy00M2Q4LThiNWEtYjFlOGRjNmIxNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDIwMzcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNDBmZmQ4NGI3YmNhMjYzY2RiZDFmNWI5NjU0NmZmNGUwZGNmN2I0Yzk4YjJhMThlM2VkNTAwYjBiNjFhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IYlaxk9HkOxXX_0eOCW5pDD-UaZ5XcKa35adb6GX9Go">
> Issue persists in latest version `0.19.1` @aome510

can you try latest `main`? I haven't released a new version in a while
